serverAddr = "frp.freefrp.net"
serverPort = 7000
auth.method = "token"
auth.token = "freefrp.net"

[[proxies]]
name = "isup-7660"
type = "tcp"
localIP = "127.0.0.1"
localPort = 7660
remotePort = 17660

[[proxies]]
name = "device1-isapi"
type = "tcp"
localIP = "192.168.23.4"
localPort = 443
remotePort = 18001

[[proxies]]
name = "device2-isapi"
type = "tcp"
localIP = "192.168.1.101"
localPort = 80
remotePort = 18002
