serverAddr = "frp.freefrp.net"
serverPort = 7000
auth.method = "token"
auth.token = "freefrp.net"

[[proxies]]
name = "isup-7660-tcp"
type = "tcp"
localIP = "isup-server"
localPort = 7660
remotePort = 17660

[[proxies]]
name = "isup-7660-udp"
type = "udp"
localIP = "isup-server"
localPort = 7660
remotePort = 17660

[[proxies]]
name = "isup-7661-tcp"
type = "tcp"
localIP = "isup-server"
localPort = 7661
remotePort = 17661

[[proxies]]
name = "isup-7661-udp"
type = "udp"
localIP = "isup-server"
localPort = 7661
remotePort = 17661
